"""add menu_version to users

Revision ID: 0f326bbc9fcb
Revises: ba3f4b60bb57
Create Date: 2026-07-31 13:27:36.716115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f326bbc9fcb'
down_revision = 'ba3f4b60bb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('menu_version')

    # ### end Alembic commands ###
