"""update appointment service relation

Revision ID: 1a68647cf3eb
Revises: 94cc6afa5b54
Create Date: 2026-06-27 21:58:02.551710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a68647cf3eb'
down_revision = '94cc6afa5b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_appointments_service_id_services", 'services', ['service_id'], ['id'])
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint("fk_appointments_service_id_services", type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
