"""add image_path to festivals

Revision ID: 49614f2dd099
Revises: abc96fd4c5a4
Create Date: 2026-06-26 16:21:13.502231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49614f2dd099'
down_revision = 'abc96fd4c5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
