"""update reminder service relation

Revision ID: 94cc6afa5b54
Revises: 49614f2dd099
Create Date: 2026-06-26 19:58:51.687479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cc6afa5b54'
down_revision = '49614f2dd099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_reminders_service_id_services", 'services', ['service_id'], ['id'])
        batch_op.drop_column('service')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('recovery_days')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint("fk_reminders_service_id_services", type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
