"""update aftercares table

Revision ID: abc96fd4c5a4
Revises: 06b3a1339d5a
Create Date: 2026-06-26 00:26:03.389198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc96fd4c5a4'
down_revision = '06b3a1339d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aftercares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint("uq_aftercares_service_id", ['service_id'])
        batch_op.create_foreign_key("fk_aftercares_service_id_services", 'services', ['service_id'], ['id'])
        batch_op.drop_column('service_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aftercares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint("fk_aftercares_service_id_services", type_='foreignkey')
        batch_op.drop_constraint("uq_aftercares_service_id", type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
