"""add unique constraint to appointment slot_id

Revision ID: df268da43f58
Revises: 1a68647cf3eb
Create Date: 2026-07-06 12:30:30.677756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df268da43f58'
down_revision = '1a68647cf3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_appointments_slot_id'), ['slot_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_appointments_slot_id'), type_='unique')

    # ### end Alembic commands ###
